# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9e39c0bfb159edce6bde537da5261e79d8fbbf7af9ca9d7ff7d9cc83a6f325e2b1dde2d98f920adf0e494d06b7725cf5e2a79ca8f7ba25b773af3e1987e502df

test:
  secret_key_base: a98c798f0ca65e0b2db8f4229364ccaf7f34c527cae5b57b5aef1a8ba8d193b3281179210a9c586e4f4e680b56ee06c78655d9f1b4772ba431eebe77b15988d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
